services:
  app:
    container_name: weather-app
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_CONNECTION_URI=${MONGO_CONNECTION_URI}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    depends_on:
      - redis
    volumes:
      - .:/app
    command: npm run dev

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
